version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bot_db
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
    container_name: telegram_bot
    restart: always
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: python src/main.py

volumes:
  postgres_data: